import { MetadataRoute } from 'next'

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'https://sistemas-jundiai.lovable.app'

// Páginas estáticas principais
const staticPages = [
  '',
  '/sobre',
  '/servicos',
  '/contato',
  '/faq',
  '/blog',
  '/produtos',
  '/sistemas',
  '/ferramentas',
  '/apis',
  '/carreiras',
]

// Posts do blog - extraídos do site original
const blogPosts = [
  '/blog/cenario-de-esports-brasileiro-em-alta-st6az',
  '/blog/lgpd-o-que-os-empresarios-precisam-saber-qo03g',
  '/blog/pesquisa-cientifica-brasileira-em-destaque-mdmfl',
  '/blog/mercado-games-mobile-no-brasil-k8me3',
  '/blog/lgpd-ciberseguranca-corporativa-brasil-i3c4w',
  '/blog/brasil-na-conquista-do-espaco-fy6ti',
  '/blog/cenario-de-e-sports-brasileiro-em-alta-dt1m8',
  '/blog/lgpd-o-novo-desafio-ciberseguranca-corporativa-bntz9',
  '/blog/descobertas-espaciais-recentes-e-brasil-9ipuw',
  '/blog/esports-brasil-mercado-em-alta-7dkdl',
  '/blog/lgpd-e-ciberseguranca-corporativa-no-brasil-58ce5',
  '/blog/pesquisa-cientifica-brasileira-em-destaque-337bp',
  '/blog/cenario-de-e-sports-brasileiro-em-alta-0y17w',
  '/blog/ciberseguranca-corporativa-pos-lgpd-ysuq0',
  '/blog/brasil-bate-recorde-em-pesquisa-cientifica-uik6e',
  '/blog/mercado-de-games-mobile-no-brasil-sddxw',
  '/blog/ciberseguranca-corporativa-pos-lgpd-q88a6',
  '/blog/avancos-em-biotecnologia-no-brasil-lxua0',
  '/blog/mercado-de-games-mobile-no-brasil-em-alta-jspvf',
  '/blog/ciber-ataques-e-o-fim-hnjsi',
  '/blog/ciencia-brasileira-em-destaque-fidz8',
  '/blog/lancamentos-de-jogos-no-brasil-2024-dd9z1',
  '/blog/ciberseguranca-corporativa-pos-lgpd-brasil-b82w4',
  '/blog/biotecnologia-no-brasil-avancos-e-perspectivas-2nhc1',
  '/blog/mercado-de-games-mobile-no-brasil-em-alta-0ibsd',
  '/blog/ciberseguranca-corporativa-pos-lgpd-yd5hp',
  '/blog/ciencia-brasileira-em-destaque-w811z',
  '/blog/jogos-2024-uma-ano-de-lancamentos-incriveis-u2tyz',
  '/blog/lgpd-ciberseguranca-corporativa-brasil-rxnmj',
  '/blog/pesquisa-cientifica-brasileira-em-destaque-nnd5k',
  '/blog/mercado-de-games-mobile-no-brasil-jczxt',
  '/blog/startups-brasileiras-em-ascensao-h7vkp',
  '/blog/pesquisa-cientifica-brasileira-em-destaque-f2q0k',
  '/blog/esports-brasil-no-mapa-asdab',
  '/blog/startups-brasileiras-em-ascensao-8n7ci',
  '/blog/biotecnologia-brasil-avancos-e-oportunidades-6i0we',
  '/blog/e-sports-brasil-feito-no-brasil-27pum',
  '/blog/startups-brasileiras-em-ascensao-02nw3',
  '/blog/brasil-brilha-em-ciencia-pesquisa-cientifica-nacional-xxdh6',
  '/blog/esports-brasil-e-um-potencia-vsacb',
  '/blog/ia-no-brasil-tendencias-2026-tn44c',
  '/blog/avancos-em-biotecnologia-no-brasil-rhyof',
  '/blog/cenario-de-e-sports-brasileiro-hoje-pcufr',
  '/blog/tendencias-de-ia-no-brasil-em-2026-n7no6',
  '/blog/ciencia-brasileira-em-destaque-hoje-l2hiu',
  '/blog/mercado-de-games-mobile-no-brasil-em-alta-gs64k',
  '/blog/tendencias-de-ia-no-brasil-em-2026-emz1s',
  '/blog/descobertas-espaciais-brasil-no-espaco-chsyp',
  '/blog/lancamentos-de-jogos-2024-brasil-acnvy',
  '/blog/startups-brasileiras-em-ascensao-87jff',
  '/blog/pesquisa-cientifica-brasileira-em-destaque-62djs',
  '/blog/mercado-de-games-mobile-no-brasil-3x5pt',
  '/blog/ia-no-brasil-o-que-o-futuro-reserva-1rylc',
  '/blog/brasil-no-espaco-ultimas-descobertas-zmvvw',
  '/blog/mercado-de-games-mobile-no-brasil-xhohf',
  '/blog/ia-no-brasil-tendencias-2026-vciju',
  '/blog/pesquisa-cientifica-brasileira-em-destaque-t7c62',
  '/blog/mercado-de-games-mobile-no-brasil-r26bq',
  '/blog/ia-brasil-2026-tendencias-e-desafios-ox1ce',
  '/blog/pesquisa-cientifica-brasileira-em-destaque-mruky',
  '/blog/como-escolher-camera-wifi',
  '/blog/o-que-e-erp',
  '/blog/seguranca-digital-empresa',
  '/blog/automacao-comercial-pequena-empresa',
  '/blog/diferenca-site-sistema-app',
  '/blog/terceirizacao-ti-vantagens',
  '/blog/crm-vendas-pequenas-empresas',
  '/blog/como-criar-loja-virtual',
  '/blog/lgpd-pequena-empresa',
  '/blog/ia-empresas-2026',
  '/blog/manutencao-preventiva-computadores',
  '/blog/monitoramento-camera-24h',
  '/blog/holograma-evento-empresarial',
  '/blog/apoio-idosos-tecnologia',
  '/blog/portaria-remota-condominio',
  '/blog/logistica-empresarial-pequena',
  '/blog/wifi-empresarial-velocidade',
  '/blog/backup-empresa-3-2-1',
  '/blog/google-meu-negocio-otimizar',
  '/blog/whatsapp-business-api',
  '/blog/controle-ponto-eletronico',
  '/blog/energia-solar-empresa',
  '/blog/site-rapido-core-web-vitals',
  '/blog/api-rest-graphql',
  '/blog/pagamentos-pix-empresa',
  '/blog/marketing-digital-pequena-empresa',
  '/blog/chatbot-whatsapp-empresas',
  '/blog/nuvem-vs-servidor-local',
  '/blog/automatizar-processos-internos',
  '/blog/controle-estoque-pequena-empresa',
  '/blog/site-institucional-vs-landing-page',
  '/blog/google-ads-pequena-empresa',
  '/blog/sistema-agendamento-online',
  '/blog/alarme-monitorado-empresa',
  '/blog/ti-saude-clinicas-consultorios',
  '/blog/pdv-restaurantes-bares',
  '/blog/treinamento-equipe-tecnologia',
  '/blog/dominio-hospedagem-email-profissional',
  '/blog/sistemas-condominios-residenciais',
  '/blog/design-system-empresa',
  '/blog/performance-site-mobile',
  '/blog/dashboard-bi-empresa',
  '/blog/loja-fisica-vs-online',
  '/blog/seguranca-senhas-empresa',
  '/blog/internet-fibra-empresa',
  '/blog/delivery-proprio-vs-ifood',
]

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const currentDate = new Date().toISOString()

  // Páginas estáticas
  const staticRoutes = staticPages.map((route) => ({
    url: `${BASE_URL}${route}`,
    lastModified: currentDate,
    changeFrequency: route === '' ? 'daily' as const : 'weekly' as const,
    priority: route === '' ? 1 : route === '/blog' ? 0.9 : 0.8,
  }))

  // Posts do blog
  const blogRoutes = blogPosts.map((route) => ({
    url: `${BASE_URL}${route}`,
    lastModified: currentDate,
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }))

  return [...staticRoutes, ...blogRoutes]
}
